### ISSUE TITLE
test登录成功后点击用户管理正常,点击其他页面报错

### ISSUE THREAD

**Issue by hugselina** [Exrick/xboot-front#13]
如题，前后端部署 然后npm run dev跑起来 登录页面用test / 123456登录 可以正常登录 这个时候控制台会报2个错误 ， 如图
![image](https://user-images.githubusercontent.com/20763416/55375574-43c81f00-553f-11e9-8050-80c37ccbb5bc.png)

然后点击 系统管理 - 用户管理 页面正常跳转 无错误 ， 
点击 系统管理 - 部门管理 页面报错 如图 （只有用户管理页面不报错，其他非付费页面都是这个错）
![image](https://user-images.githubusercontent.com/20763416/55375618-6d814600-553f-11e9-8c96-32ff24863766.png)

度娘告诉我是JS文件没有放在static ? 
能告知下原因么？

另外问下 登录页面 加载0.js - 100.js这个是什么作用？ 登录页面打开后 93个request 感觉不太科学

**Comment by hugselina** [comment]
补充一下 这个不是打包 是dev后访问本地9999的页面

**Comment by Exrick** [comment]
第一个错根据ip获取天气信息报的错 由于本地无法获取ip 解析空字符json报的错 近期提交修复
第二个错未知异常，建议删除node_modules重新使用npm 尝试

**Comment by hugselina** [comment]
好的 我尝试一下 谢谢
