### ISSUE TITLE
数据字典bug

### ISSUE THREAD

**Issue by leslieeilsel** [Exrick/xboot-front#15]
如图：
[![Ec6058.gif](https://s2.ax1x.com/2019/05/09/Ec6058.gif)](https://imgchr.com/i/Ec6058)

**Comment by Exrick** [comment]
额 这个是细节问题 不算BUG
因为添加与编辑用的同一个form，每次编辑前可以使用Form的resetFields方法将所有字段值重置为空并移除校验结果，后期提交将完善该细节，感谢提出！

**Comment by Exrick** [comment]
@leslieeilsel 已提交优化细节 请确认

**Comment by leslieeilsel** [comment]
> @leslieeilsel 已提交优化细节 请确认

已确认，细节已优化
:+1:
