### ISSUE TITLE
考虑做crud或代码生成器吗？

### ISSUE THREAD

**Issue by blueway** [Exrick/xboot-front#4]
考虑做crud或代码生成器吗？

**Comment by Exrick** [comment]
这个是vue项目...我最多只能提供空白crud模板文件不知能否满足你的需求

**Comment by Exrick** [comment]
目前只有后端代码生成器

**Comment by blueway** [comment]
空白crud文件也行，是看到一个模块文件超过500多行，　一个用户管理模块超过一千行，生产力不高啊。适当的封装一下crud的一些常规操作，主要是modal这些Form和操作方法，太多了。
